### ISSUE TITLE
Delete duplicate period

### ISSUE THREAD

**Issue by atomrab** [periodo/periodo-data#55] opened 2018-11-02 16:44 UTC
An LC subject heading was duplicated again. When you have a chance, please delete http://n2t.net/ark:/99152/p06c6g3tktj (this was from accidental inclusion of a period from a subheading, when the period from the main heading already existed).

**Comment by rybesh** [comment] 2021-06-09 15:29
duplicate of #67

**Closed by rybesh** 2021-06-09 15:29 UTC
Labels: bug, data
